version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: fatra-frontend:latest
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
      # - NEXT_PUBLIC_API_URL=http://your-api-url:port
